export PF_ID

#=
    Protocol families
=#
PF_ID = (
    PF_UNSPEC = 0,          # Unspecified
    PF_LOCAL = 1,           # Local to host (pipes and file-domain)
    PF_UNIX = 1,     # POSIX name for PF_LOCAL
    PF_FILE = 1,     # Another non-standard name for PF_LOCAL
    PF_INET = 2,            # IP protocol family
    PF_AX25 = 3,            # Amateur Radio AX.25
    PF_IPX = 4,             # Novell Internet Protocol
    PF_APPLETALK = 5,       # Appletalk DDP
    PF_NETROM = 6,          # Amateur radio NetROM
    PF_BRIDGE = 7,          # Multiprotocol bridge
    PF_ATMPVC = 8,          # ATM PVCs
    PF_X25 = 9,             # Reserved for X.25 project
    PF_INET6 = 10,          # IP version 6
    PF_ROSE = 11,           # Amateur Radio X.25 PLP
    PF_DECnet = 12,         # Reserved for DECnet project
    PF_NETBEUI = 13,        # Reserved for 802.2LLC project
    PF_SECURITY = 14,       # Security callback pseudo AF
    PF_KEY = 15,            # PF_KEY key management API
    PF_NETLINK = 16,                     
    PF_ROUTE = 16,  # Alias to emulate 4.4BSD
    PF_PACKET = 17,         # Packet family
    PF_ASH = 18,            # Ash
    PF_ECONET = 19,         # Acorn Econet
    PF_ATMSVC = 20,         # ATM SVCs
    PF_RDS = 21,            # RDS sockets
    PF_SNA = 22,            # Linux SNA Project
    PF_IRDA = 23,           # IRDA sockets
    PF_PPPOX = 24,          # PPPoX sockets
    PF_WANPIPE = 25,        # Wanpipe API sockets
    PF_LLC = 26,            # Linux LLC
    PF_IB = 27,             # Native InfiniBand address
    PF_MPLS = 28,           # MPLS
    PF_CAN = 29,            # Controller Area Network
    PF_TIPC = 30,           # TIPC sockets
    PF_BLUETOOTH = 31,      # Bluetooth sockets
    PF_IUCV = 32,           # IUCV sockets
    PF_RXRPC = 33,          # RxRPC sockets
    PF_ISDN = 34,           # mISDN sockets
    PF_PHONET = 35,         # Phonet sockets
    PF_IEEE802154 = 36,     # IEEE 802.15.4 sockets
    PF_CAIF = 37,           # CAIF sockets
    PF_ALG = 38,            # Algorithm sockets
    PF_NFC = 39,            # NFC sockets
    PF_VSOCK = 40,          # vSockets
    PF_KCM = 41,            # Kernel Connection Multiplexor
    PF_QIPCRTR = 42,        # Qualcomm IPC Router
    PF_SMC = 43,            # SMC sockets
    PF_MAX = 44             # For now.
)

#=
    Address families
=#
AF_ID = (
    AF_UNSPEC = PF_ID.PF_UNSPEC,
    AF_LOCAL = PF_ID.PF_LOCAL,
    AF_UNIX = PF_ID.PF_UNIX,
    AF_FILE = PF_ID.PF_FILE,
    AF_INET = PF_ID.PF_INET,
    AF_AX25 = PF_ID.PF_AX25,
    AF_IPX = PF_ID.PF_IPX,
    AF_APPLETALK = PF_ID.PF_APPLETALK,
    AF_NETROM = PF_ID.PF_NETROM,
    AF_BRIDGE = PF_ID.PF_BRIDGE,
    AF_ATMPVC = PF_ID.PF_ATMPVC,
    AF_X25 = PF_ID.PF_X25,
    AF_INET6 = PF_ID.PF_INET6,
    AF_ROSE = PF_ID.PF_ROSE,
    AF_DECnet = PF_ID.PF_DECnet,
    AF_NETBEUI = PF_ID.PF_NETBEUI,
    AF_SECURITY = PF_ID.PF_SECURITY,
    AF_KEY = PF_ID.PF_KEY,
    AF_NETLINK = PF_ID.PF_NETLINK,
    AF_ROUTE = PF_ID.PF_ROUTE,
    AF_PACKET = PF_ID.PF_PACKET,
    AF_ASH = PF_ID.PF_ASH,
    AF_ECONET = PF_ID.PF_ECONET,
    AF_ATMSVC = PF_ID.PF_ATMSVC,
    AF_RDS = PF_ID.PF_RDS,
    AF_SNA = PF_ID.PF_SNA,
    AF_IRDA = PF_ID.PF_IRDA,
    AF_PPPOX = PF_ID.PF_PPPOX,
    AF_WANPIPE = PF_ID.PF_WANPIPE,
    AF_LLC = PF_ID.PF_LLC,
    AF_IB = PF_ID.PF_IB,
    AF_MPLS = PF_ID.PF_MPLS,
    AF_CAN = PF_ID.PF_CAN,
    AF_TIPC = PF_ID.PF_TIPC,
    AF_BLUETOOTH = PF_ID.PF_BLUETOOTH,
    AF_IUCV = PF_ID.PF_IUCV,
    AF_RXRPC = PF_ID.PF_RXRPC,
    AF_ISDN = PF_ID.PF_ISDN,
    AF_PHONET = PF_ID.PF_PHONET,
    AF_IEEE802154 = PF_ID.PF_IEEE802154,
    AF_CAIF = PF_ID.PF_CAIF,
    AF_ALG = PF_ID.PF_ALG,
    AF_NFC = PF_ID.PF_NFC,
    AF_VSOCK = PF_ID.PF_VSOCK,
    AF_KCM = PF_ID.PF_KCM,
    AF_QIPCRTR = PF_ID.PF_QIPCRTR,
    AF_SMC = PF_ID.PF_SMC,
    AF_MAX = PF_ID.PF_MAX
)
